### PR TITLE
ETH-146: Update subgraph

### PR DESCRIPTION
**Pull request by jtakalai**

### CODE REVIEW

**Comment by tumppi** [comment]
Are there any reasons why this could not be reviewed and merged? Would love to deploy this subgraph to The Graph and use it on core-frontend. Ping @jtakalai @samt1803.

**Review by samt1803 — APPROVED** [review]
Is there a reason this PR is still in draft?
Changes look good to me, but I am not that familiar with the data-union codebase.
I didn't try it out.

**Comment by jtakalai** [comment]
I should probably take this in works and finish it at some point... it was a bit of a cleanup thing on the repo but then more urgent things came I guess.

**Comment by jtakalai** [comment]
Mostly this is out of date and WIP. TheGraph subgraph for data unions exists and is deployed (in master).

**Pull request closed without merging**
